repository:
  name: dotfiles
  description: Declarative configurations for my NixOS system with flakes, home manager
  homepage: https://github.com/c0d3h01/dotfiles
  private: false
  default_branch: NixOS
  has_issues: true
  has_wiki: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: Feature request or improvement
  - name: auto-merge
    color: 1d76db
    description: Automatically merge this pull request when CI passes

collaborators:
  - username: c0d3h01
    permission: admin
