repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: "1.21.0"
    hooks:
      - id: alejandra
  - repo: https://github.com/nerdypepper/statix
    rev: "0.6.0"
    hooks:
      - id: statix
  - repo: https://github.com/astro/deadnix
    rev: "0.6.0"
    hooks:
      - id: deadnix