keys:
  - &c0d3h01 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICSjL8HGjiSAnLHupMZin095bql7A8+UDfc7t9XCZs8l
  - &c0d3h01_nix age1226wa2fhrhm9cdqs5xght34xwc4vrm2a42mgt3zasvatc98p7ddsft4ux5

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *c0d3h01_nix
          - *c0d3h01
