keys:
  - &admin_harshal C94AADFF16519330791C0F98A2D5F421ECBFED37
  - &c0d3h01_laptop age1slc5p3prmn8hsldxezvsaz29luuhsjxsj7gspk8p506d4xw9rstqeyy0ls

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *c0d3h01_laptop
        gpg:
          - *admin_harshal
