keys:
  - &harshal age1slc5p3prmn8hsldxezvsaz29luuhsjxsj7gspk8p506d4xw9rstqeyy0ls
  - &eva age1eqd59l6ll6sjsqm4gj675kq52mnt6799jghzleaty0202ltk852qaxw7c8

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *harshal
          - *eva
