color_theme = "gruvbox_dark"
theme_background = false
rounded_corners = true
vim_keys = true
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_tree = false
proc_aggregate = false
cpu_single_graph = false
show_battery = true
save_config_on_exit = false
