[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
blinking = "Always"
style = "Block"

[mouse]
hide_when_typing = true

[window]
startup_mode = "Fullscreen"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"

[scrolling]
history = 10000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false
