on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Build nixos configs
        run: nix build --dry-run .#nixosConfigurations.c0d3h01.config.system.build.toplevel