name: Validate Flake Lock

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            ref:
                required: false
                type: string
    push:
        paths:
            - "**.lock"
            - "!home/**"

permissions: {}

jobs:
    check-flake:
        name: Check Lock
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  ref: ${{ inputs.ref && inputs.ref || github.ref_name }}
                  persist-credentials: false

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@v15

            - name: Check flake.lock
              run: nix run github:tgirlcloud/pkgs#locker
