name: "Flake.lock"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Upd flake inputs"
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-labels: |
            flake-locks
