name: "Flake.lock: update Nix dependencies"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          token: ${{ secrets.DOTFILES }}
          pr-labels: |
            dependencies
            automated

      - if: steps.update.outputs.pull-request-number
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.DOTFILES }}
