name: Update README with dotfiles root structure

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tree structure
        run: |
          echo '```' > README_TREE.md
          tree -L 3 --noreport >> README_TREE.md
          echo '```' >> README_TREE.md

      - name: Update README.md
        run: |
          BADGE="[![built with nix](https://img.shields.io/static/v1?logo=nixos&logoColor=white&label=&message=Built%40with%40Nix&color=41439a)](https://builtwithnix.org)"
          echo "$BADGE" > TEMP.md
          echo "" >> TEMP.md  # Add an empty line
          echo "## 📂 Dotfiles Structure" >> TEMP.md
          cat README_TREE.md >> TEMP.md
          mv TEMP.md README.md
          rm README_TREE.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "upd: README structure"
          branch: main
          file_pattern: README.md
          commit_user_name: "Readme Bot"
          commit_author: "Readme Bot <actions@github.com>"
          skip_dirty_check: false
          skip_fetch: false
          push_options: '--force'
