name: "Update submodules"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "51 2 * * *"

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.DOTFILES }}

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update SubModules
          token: ${{ secrets.DOTFILES }}

      - name: Merge PR
        if: steps.pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.pr.outputs.pull-request-number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.DOTFILES }}
